<?php
/**
 * Do not edit this file. Edit the config files in /config instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 * https://github.com/roots/bedrock/blob/master/web/wp-config.php
 *
 * All project config lives in /config:
 *   config/application.php              shared settings (DB, URLs, salts, defines)
 *   config/environments/development.php local + Pantheon dev/multidev
 *   config/environments/staging.php     Pantheon test
 *   config/environments/production.php  Pantheon live
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/config/application.php';

if (!defined('ABSPATH')) {
    define('ABSPATH', __DIR__ . '/wp/');
}

require_once ABSPATH . 'wp-settings.php';
